from shiny import ui
from utils.styling import (
    create_data_input_head,
    hero_section_class,
    metric_card_class,
    control_card_class,
    action_buttons_class,
    stats_grid_class,
    metric_list_class
)


def data_input_ui():
    # 1. DATA INPUT PANEL -----------------------------------
    return ui.nav_panel("Data Input",
        # Include centralized styling
        create_data_input_head(),
        ui.div(
            {"class": "container-fluid p-4"},

            # Hero Section
            ui.div(
                {"class": hero_section_class()},
                ui.h1([
                    ui.span("📁", {"style": "margin-right: 0.5rem; "
                                           "font-size: 1.6rem;"}),
                    "Data Upload"
                ], {"class": "data-input-title"}),
                ui.p("Upload analysis results generated by SPAC workflows. "
                     "The app comes preloaded with a ",
                     {"class": "text-muted mb-1"}),
                ui.p([
                    ui.a("scimap demo dataset",
                         href="https://scimap.xyz/tutorials/md/"
                              "demo_data_scimap/",
                         target="_blank",
                         rel="noopener noreferrer",
                         class_="text-decoration-none"),
                    " that was analyzed using the SPAC ",
                    ui.a("lymph node analysis pipeline",
                         href="https://github.com/FNLCR-DMAP/SCSAWorkflow/"
                              "blob/address-reviewer-comments/paper/examples/"
                              "lymphnode_analysis.ipynb",
                         target="_blank",
                         rel="noopener noreferrer",
                         class_="text-decoration-none"),
                    " for demonstration."
                ], {"class": "text-muted mb-1"}),
                ui.p("Supports .h5ad files and .pickle files "
                     "generated with Python 3.9.13",
                     {"class": "text-muted small fst-italic mb-0"})
            ),

            # Main Content Area
            ui.div(
                {"class": "row"},

                # Upload and Data Overview Section
                ui.div(
                    {"class": "col-lg-8 mb-4"},
                    ui.div(
                        {"class": "card control-card"},
                        ui.div(
                            {"class": "card-body"},
                            ui.h5("📁 Data Upload", {"class": "card-title mb-3"}),
                            ui.div(
                                {"class": "upload-area"},
                                ui.input_file(
                                    "input_file",
                                    "Choose a file to upload (.h5ad or .pickle):",
                                    multiple=False,
                                    width="100%"
                                ),
                                # ADDED: Helper text to show supported file types
                                ui.p(
                                    "Supported types: .pickle, .h5ad",
                                    style="font-size: 0.9em; font-style: italic; color: #6c757d;"
                                )
                            )
                        )
                    ),

                    # Data Metrics Grid
                    ui.div(
                        {"class": stats_grid_class()},
                        ui.div(
                            {"class": metric_card_class()},
                            ui.div(
                                {"class": "card-body"},
                                ui.div(
                                    {"class": "d-flex align-items-center mb-2"},
                                    ui.span("📊", {"class": "me-2", 
                                                   "style": "font-size: 1.2rem;"}),
                                    ui.h6("Number of Cells", 
                                          {"class": "mb-0 fw-semibold text-primary"})
                                ),
                                ui.div({"class": "metric-output text-center"},
                                    ui.output_text("print_rows")
                                )
                            )
                        ),
                        ui.div(
                            {"class": "card metric-card"},
                            ui.div(
                                {"class": "card-body"},
                                ui.div(
                                    {"class": "d-flex align-items-center mb-2"},
                                    ui.span("🧬", {"class": "me-2", "style": "font-size: 1.2rem;"}),
                                    ui.h6("Number of Features", {"class": "mb-0 fw-semibold text-primary"})
                                ),
                                ui.div({"class": "metric-output text-center"},
                                    ui.output_text("print_columns")
                                )
                            )
                        ),
                        ui.div(
                            {"class": "card metric-card"},
                            ui.div(
                                {"class": "card-body"},
                                ui.div(
                                    {"class": "d-flex align-items-center mb-2"},
                                    ui.span("🏷️", {"class": "me-2", "style": "font-size: 1.2rem;"}),
                                    ui.h6("Annotations", {"class": "mb-0 fw-semibold text-success"})
                                ),
                                ui.div({"class": metric_list_class()},
                                    ui.output_ui("formatted_obs_names")
                                )
                            )
                        ),
                        ui.div(
                            {"class": "card metric-card"},
                            ui.div(
                                {"class": "card-body"},
                                ui.div(
                                    {"class": "d-flex align-items-center mb-2"},
                                    ui.span("📋", {"class": "me-2", "style": "font-size: 1.2rem;"}),
                                    ui.h6("Associated Tables", {"class": "mb-0 fw-semibold text-info"})
                                ),
                                ui.div({"class": "metric-list"},
                                    ui.output_ui("formatted_obsm_names")
                                )
                            )
                        ),
                        ui.div(
                            {"class": "card metric-card"},
                            ui.div(
                                {"class": "card-body"},
                                ui.div(
                                    {"class": "d-flex align-items-center mb-2"},
                                    ui.span("📊", {"class": "me-2", "style": "font-size: 1.2rem;"}),
                                    ui.h6("Tables", {"class": "mb-0 fw-semibold text-warning"})
                                ),
                                ui.div({"class": "metric-list"},
                                    ui.output_ui("formatted_layers_names")
                                )
                            )
                        ),
                        ui.div(
                            {"class": "card metric-card"},
                            ui.div(
                                {"class": "card-body"},
                                ui.div(
                                    {"class": "d-flex align-items-center mb-2"},
                                    ui.span("🗃️", {"class": "me-2", "style": "font-size: 1.2rem;"}),
                                    ui.h6("Unstructured Data", {"class": "mb-0 fw-semibold text-secondary"})
                                ),
                                ui.div({"class": "metric-list"},
                                    ui.output_ui("formatted_uns_names")
                                )
                            )
                        )
                    )
                ),

                # Data Controls Section
                ui.div(
                    {"class": "col-lg-4 mb-4"},
                    ui.div(
                        {"class": control_card_class()},
                        ui.div(
                            {"class": "card-header bg-light"},
                            ui.h5("🔧 Data Controls", {"class": "mb-0"})
                        ),
                        ui.div(
                            {"class": "card-body"},
                            ui.input_checkbox(
                                "subset_select_check",
                                "Enable Data Subsetting",
                                False
                            ),
                            ui.div({"class": "mb-3"}, id="main-subset_anno_dropdown"),
                            ui.div({"class": "mb-3"}, id="main-subset_label_dropdown"),

                            ui.div(
                                {"class": action_buttons_class()},
                                ui.input_action_button(
                                    "go_subset",
                                    "Apply Subset",
                                    class_="btn btn-success flex-fill"
                                ),
                                ui.input_action_button(
                                    "restore_data",
                                    "Restore Data",
                                    class_="btn btn-outline-warning flex-fill"
                                )
                            ),

                            ui.div(
                                {"class": "mt-3 p-3 bg-light rounded"},
                                ui.h6("Subset History", {"class": "mb-2"}),
                                ui.div({"class": "metric-output small"},
                                    ui.output_text("print_subset_history")
                                )
                            )
                        )
                    )
                )
            ),

            # Annotation Summary Section
            ui.div(
                {"class": "row"},
                ui.div(
                    {"class": "col-12"},
                    ui.div(
                        {"class": "card summary-card"},
                        ui.div(
                            {"class": "card-header bg-light"},
                            ui.h5("📊 Annotation Summary with Top 10 Labels", {"class": "mb-0"})
                        ),
                        ui.div(
                            {"class": "card-body"},
                            ui.output_ui("annotation_labels_display")
                        )
                    )
                )
            )
        )
    )